---
title: "NRE538_Resampling"
author: "Feng-Hsun Chang"
date: "2016.11.22"
output: 
  html_document:
    code_folding: show
    highlight: textmate
    keep_md: yes
    number_sections: true
    theme: flatly
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: true
      toc_depth: 4

---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(plyr)
library(reshape2)
library(magrittr)
library(ggplot2)
library(grid)
library(scales)
library(bbmle)
library(knitr)
theme_set(theme_bw())
```

\newcommand\expect[1]{\mathbb{E}\left[{#1}\right]}
\newcommand\var[1]{\mathrm{Var}\left[{#1}\right]}
\newcommand\loglik{\ell}
\newcommand\prob[1]{\mathbb{P}\left[{#1}\right]}
\newcommand{\dd}[1]{\mathrm{d}{#1}}

* What does the shape of the likelihood surface tell us about the identifiability of the parameters? What does it say about which aspects of the data are most informative?

The following is the likelihood contour of the original model with the `logit` function describing the hazard function and the `logit` function depends linearly on the carapath length ($L_i$), i.e. $\mathrm{logit}(p_i) = a + b\,L_i,$. 

This shape indicates that on a certain axis of parameter "a" and "b" combination, the likelihood of observing this given data are similar. Along this combination axis, the data are not informative to tell if the model is good enough to describe (or explain?) the data. 

Here I make the infection hazard a function of carapace length. I first try the hazard function in the Michaelis-Menten form. 

$$\lambda(L) = \frac{r_mL}{K+L}$$,  
where $r_m$ is the highest probability an individual could be infected, and $K$ describes the carapace length where the individual has half of the $r_m$. 

Accordingly, the CDF the determines the probability of an individual to be seropositive is 

$$\prob{X_i=\text{pos}} = 1 - \exp{\left[-\int_0^L\!\lambda(L)\dd{L}\right]} = 1 - \exp{\left [-r_m\,K (\frac{L}{K} - Log(1 + \frac{L}{K}) \right ]}$$.
